-

diff --git a/bin/php-builder b/bin/php-builder
--- a/bin/php-builder
+++ b/bin/php-builder
@@ -20,32 +20,34 @@ function build {
   VERSION="$1"
   VARIANT="$2"
 
-  make clean > /dev/null 2>&1
-  git fetch --all --tags > /dev/null 2>&1
-  git checkout --force "refs/tags/php-$VERSION" > /dev/null 2>&1
-
-  BUILD_DIR="/usr/local/php/builds/$VERSION"
-  if ! [[ -z $VARIANT ]]; then
-    FULL_VERSION="$VERSION-$VARIANT"
-    BUILD_DIR="$BUILD_DIR-$VARIANT"
-  else
-    FULL_VERSION="$VERSION"
-  fi
-  PEAR_DIR="${BUILD_DIR}/lib"
-
-  CONFIGURE_OPTIONS="--localstatedir=/usr/local/var --with-iconv-dir=/usr --enable-dba --with-ndbm=/usr --enable-exif \
---enable-soap --enable-wddx --enable-ftp --enable-sockets --enable-zip --enable-pcntl --enable-shmop \
+  CONFIGURE_OPTIONS="--localstatedir=/usr/local/var --with-iconv-dir=/usr \
+--enable-sockets --enable-zip --enable-shmop \
 --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-mbstring --enable-mbregex \
---enable-calendar --with-zlib=/usr/local/opt/zlib --with-ldap --with-ldap-sasl=/usr --with-xmlrpc \
---with-kerberos=/usr --with-xsl=/usr --with-gd --enable-gd-native-ttf --with-freetype-dir=/usr/local/opt/freetype \
+--enable-calendar --with-zlib=/usr/local/opt/zlib --with-xmlrpc \
 --with-jpeg-dir=/usr/local/opt/jpeg --with-png-dir=/usr/local/opt/libpng --with-gettext=/usr/local/opt/gettext \
---with-snmp=/usr --with-libedit --with-mhash --with-curl --with-bz2=/usr --with-openssl=/usr/local/opt/openssl \
---enable-bcmath \
+--with-libedit --with-mhash --with-curl --with-bz2=/usr \
 --with-pgsql=/usr/local/opt/postgresql --with-pdo-pgsql=/usr/local/opt/postgresql \
---with-iodbc --with-pdo-odbc=generic,/usr,iodbc"
+"
 
-  if [[ "x$VARIANT" == "xdebug" ]]; then
-      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-zend-signals --enable-debug --enable-dtrace --enable-maintainer-zts"
+  if [[ $VARIANT != *light* ]]; then
+    CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS\
+--enable-pcntl \
+--with-kerberos=/usr --with-xsl=/usr --with-gd --enable-gd-native-ttf --with-freetype-dir=/usr/local/opt/freetype \
+--with-snmp=/usr \
+--enable-dba --with-ndbm=/usr --enable-exif
+--enable-soap --enable-wddx --enable-ftp \
+--with-ldap --with-ldap-sasl=/usr \
+--enable-bcmath \
+--with-iodbc --with-pdo-odbc=generic,/usr,iodbc \
+"
+  fi
+
+  vercomp $VERSION "5.6.0"
+  # < 5.3.0
+  if [[ $? == 2 ]]; then
+      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-openssl=$(brew --prefix openssl)"
+  else
+      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-openssl-dir=$(brew --prefix openssl)"
   fi
 
   vercomp $VERSION "5.3.0"
@@ -53,13 +55,18 @@ function build {
   if [[ $? == 2 ]]; then
       export PATH="/usr/local/flex-2.5.4/bin/:$PATH"
   else
-      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-mysql=mysqlnd --with-pdo-mysql=mysqlnd --with-gmp=/usr/local/opt/gmp"
+      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS \
+--with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-mysql=mysqlnd --with-pdo-mysql=mysqlnd \
+--with-gmp=/usr/local/opt/gmp \
+"
   fi
 
   vercomp $VERSION "5.3.2"
   # > 5.3.2
   if [[ $? == 1 ]]; then
-      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-fpm --with-fpm-user=_www --with-fpm-group=_www"
+      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS \
+--enable-fpm --with-fpm-user=_www --with-fpm-group=_www \
+"
   fi
 
   # < 5.4.0
@@ -69,6 +76,15 @@ function build {
       export PHP_AUTOCONF="/usr/local/autoconf-2.59/bin/autoconf"
   fi
 
+  BUILD_DIR="/usr/local/php/builds/$VERSION"
+  if ! [[ -z $VARIANT ]]; then
+      FULL_VERSION="$VERSION-$VARIANT"
+      BUILD_DIR="$BUILD_DIR-$VARIANT"
+  else
+      FULL_VERSION="$VERSION"
+  fi
+  PEAR_DIR="${BUILD_DIR}/lib"
+
   CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --prefix=${BUILD_DIR} \
 --mandir=${BUILD_DIR}/share/man \
 --sysconfdir=${BUILD_DIR}/etc \
@@ -76,15 +92,44 @@ function build {
 --with-config-file-scan-dir=${BUILD_DIR}/etc/conf.d \
 --with-pear=${PEAR_DIR}"
 
+  if [[ $VARIANT != *no-zts* ]]; then
+    CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-maintainer-zts"
+  fi
+
+  if [[ $VARIANT == *debug* ]]; then
+    if [[ $VARIANT != *no-signals* ]]; then
+      CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-zend-signals"
+    fi
+    CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-debug --enable-dtrace"
+  fi
+
+  echo ${BUILD_DIR}
+  echo ${CONFIGURE_OPTIONS}
+  echo -en "\033[0;31mDo you confirm ?\033[0m "
+  read -r -p '[Y/n]' confirm
+  case $confirm in
+    [yY][eE][sS]|[yY]|"")
+        ;;
+    *)
+        echo "Aborted!"
+        exit 2
+        ;;
+  esac
+
   mkdir -p ${BUILD_DIR}/etc/conf.d/
   touch ${BUILD_DIR}/etc/php.ini
-  ln -nsf /usr/local/php/etc/php-fpm.conf ${BUILD_DIR}/etc/
+  ln -nsf /usr/local/php/etc/php-fpm.conf ${BUILD_DIR}/etc
   ln -nsf /usr/local/php/etc/customisations.ini ${BUILD_DIR}/etc/conf.d/99-customisations.ini
   echo "include_path=\".:$PEAR_DIR\"" > ${BUILD_DIR}/etc/conf.d/99-pear.ini
 
+  ./vcsclean
+  make clean > /dev/null 2>&1
+  git fetch --all --tags > /dev/null 2>&1
+  git checkout --force "refs/tags/php-$VERSION" > /dev/null 2>&1
+
   (./buildconf --force \
     && \
-  ./configure $CONFIGURE_OPTIONS \
+   YACC=/usr/local/Cellar/bison/2.7/bin/bison ./configure $CONFIGURE_OPTIONS \
    && \
   # make clean && make) > /dev/null  2>&1 \
   make clean && make) \
